# Generated by Django 5.2 on 2025-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
