# Generated by Django 5.2 on 2025-05-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
